import js from '@eslint/js'
import globals from 'globals'
import vue from 'eslint-plugin-vue'
import vueParser from 'vue-eslint-parser'
import tsParser from '@typescript-eslint/parser'
import tsPlugin from '@typescript-eslint/eslint-plugin'
import unusedImports from 'eslint-plugin-unused-imports'
import eslintConfigPrettier from 'eslint-config-prettier'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

function loadAutoImportGlobals() {
  // Generated by `unplugin-auto-import` (see `vite.config.ts`)
  // Format typically: { globals: { ref: true, computed: true, ... } }
  const p = path.join(__dirname, 'eslintrc', '.eslintrc-auto-import.json')
  try {
    if (!fs.existsSync(p)) return {}
    const raw = fs.readFileSync(p, 'utf8')
    const json = JSON.parse(raw)
    if (json && typeof json === 'object' && json.globals && typeof json.globals === 'object') return json.globals
    return {}
  } catch {
    return {}
  }
}

const autoImportGlobals = loadAutoImportGlobals()
const isProd = process.env.NODE_ENV === 'production'

const commonRules = {
  'no-debugger': isProd ? 'error' : 'warn',
  'no-console': isProd ? ['warn', { allow: ['warn', 'error'] }] : 'off',
  // 项目中存在大量全局变量（auto-import/$window 等），避免噪音
  'no-undef': 'off',
  'no-unused-vars': 'off',
  eqeqeq: ['warn','smart'],
  'prefer-const': 'warn',
  'no-var': 'warn',
  'no-extra-boolean-cast': 'warn',
  'no-empty-pattern': 'warn',
  'no-prototype-builtins': 'warn',
}

const commonTsRules = {
  ...commonRules,
  '@typescript-eslint/no-unused-vars': [
    'warn',
    {
      // 函数参数：只报告最后一个被使用参数之后的未使用参数
      // 回调入参、v-slot 参数等位于"已用参数"之前的均忽略
      args: 'after-used',
      argsIgnorePattern: '^_',
      varsIgnorePattern: '^_',
      caughtErrorsIgnorePattern: '^_',
      // 数组解构跳过项，如 const [, second] = arr
      destructuredArrayIgnorePattern: '^_',
      // 对象解构中用 rest 消费剩余属性时忽略已解构但未使用的兄弟项
      ignoreRestSiblings: true,
    },
  ],
  '@typescript-eslint/consistent-type-imports': [
    'warn',
    { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
  ],
}

export default [
  // Global ignores
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/lib/**',
      '**/.vite/**',
      '**/coverage/**',
      '**/*.min.*',
      // generated d.ts
      'types/**/*.d.ts',
    ],
  },

  // Base JS rules
  js.configs.recommended,

  // Project-wide relaxations
  {
    rules: {
      'no-irregular-whitespace': 'off',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-useless-escape': 'warn',
    },
  },

  // Vue SFC rules
  ...vue.configs['flat/recommended'],

  // JS/JSX (ESM)
  {
    files: ['**/*.{mjs,js,jsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    rules: {
      ...commonRules,
    },
  },

  // JS (CommonJS)
  {
    files: ['**/*.cjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'commonjs',
      globals: {
        ...globals.node,
      },
    },
    rules: {
      ...commonRules,
    },
  },

  // TS/TSX
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parser: tsParser,
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        ...autoImportGlobals,
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
      'unused-imports': unusedImports,
    },
    rules: {
      ...commonTsRules,
      'unused-imports/no-unused-imports': 'warn',
    },
  },

  // Vue (script/script setup uses TS parser)
  {
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: tsParser,
        ecmaVersion: 'latest',
        sourceType: 'module',
        extraFileExtensions: ['.vue'],
      },
      globals: {
        ...globals.browser,
        ...globals.node,
        ...autoImportGlobals,
      },
    },
    plugins: {
      vue,
      '@typescript-eslint': tsPlugin,
      'unused-imports': unusedImports,
    },
    rules: {
      ...commonTsRules,
      'unused-imports/no-unused-imports': 'error',
      'vue/multi-word-component-names': 'off',
      'vue/attribute-hyphenation': 'off',
      'vue/v-on-event-hyphenation': 'off',
      'vue/attributes-order': 'off',
      'vue/no-unused-vars': 'warn',
      // 'vue/require-v-for-key': 'warn',
      'vue/no-parsing-error': 'warn',
      'vue/first-attribute-linebreak': 'off',
      'vue/v-slot-style': 'off',
      'vue/no-required-prop-with-default': 'off',
      'vue/require-default-prop': 'off',
      'vue/require-prop-types': 'off',
      'vue/require-prop-type-constructor': 'off',
      'vue/no-useless-template-attributes': 'warn',
      'vue/no-v-html': 'off',
      // 'vue/no-v-text-v-html-on-component': 'warn',
      'vue/require-toggle-inside-transition': 'warn',
    },
  },

  // Turn off formatting rules that conflict with Prettier
  eslintConfigPrettier,
]
